from random import choice
print("====== DESAFIO 19 ======")
print("Sobre o codigo: Um professor quer sortear um dos seus quatro alunos", end='')
print(" para apagar o quadro. Faca um programa que ajude ele, lendo o nome deles", end='')
print(" e escrevendo o nome do escolhido")
aluno1 = input("Digite o nome do primeiro aluno: ")
aluno2 = input("Digite o nome do segundo aluno: ")
aluno3 = input("Digite o nome do terceiro aluno: ")
aluno4 = input("Digite o nome do quarto aluno: ")
print(choice([aluno1, aluno2, aluno3, aluno4]))
# print("O aluno escolhido foi {}".format(choice([aluno1, aluno2, aluno3, aluno4])))